name: Create Cypress report
on: [push]

defaults:
  run:
    working-directory: frontend

jobs:
  cypress-e2e-chrome88:
    name: Run on Chrome 88
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - uses: actions/checkout@v2

      - name: Run Cypress tests
        run: yarn cypress:run
        continue-on-error: true
